@php $isTr = app()->getLocale() === 'tr'; $changes = collect($professional['changes'] ?? []); @endphp
<div class="space-y-4">
    <div><h2 class="text-lg font-semibold text-gray-900 dark:text-white">{{ $isTr ? 'Değişiklik geçmişi' : 'Change history' }}</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ $isTr ? 'Google Ads hesabında kim, ne zaman, hangi kaynağı değiştirdi? Provider Change Event kayıtları.' : 'Who changed what and when in Google Ads? Provider Change Event records.' }}</p></div>
    <div class="rounded-xl bg-blue-50 px-4 py-3 text-sm text-blue-800 ring-1 ring-inset ring-blue-100 dark:bg-blue-500/10 dark:text-blue-200 dark:ring-blue-500/20">{{ $isTr ? 'Google API yalnız yakın dönem Change Event verisini verir; MOXDOP topladıkça bu kayıtları kendi veri havuzunda korur. Değişiklik ile performans hareketi birlikte görülebilir ama korelasyon otomatik olarak nedensellik sayılmaz.' : 'Google API exposes only recent Change Events; MOXDOP preserves collected records. A change may correlate with performance movement, but correlation is not automatically treated as causation.' }}</div>
    <section class="overflow-hidden rounded-xl bg-white ring-1 ring-inset ring-gray-200 dark:bg-gray-900 dark:ring-gray-800">
        <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-xs text-gray-500 dark:bg-white/[0.02]"><tr><th class="px-4 py-2 text-left">{{ $isTr ? 'Tarih' : 'Date' }}</th><th class="px-3 py-2 text-left">{{ $isTr ? 'Kullanıcı' : 'User' }}</th><th class="px-3 py-2 text-left">{{ $isTr ? 'Kaynak türü' : 'Resource type' }}</th><th class="px-3 py-2 text-left">{{ $isTr ? 'İşlem' : 'Operation' }}</th><th class="px-3 py-2 text-left">Client</th><th class="px-4 py-2 text-left">{{ $isTr ? 'Detay' : 'Details' }}</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">
            @forelse ($changes as $row)
                @php $m = is_array($row['metadata'] ?? null) ? $row['metadata'] : []; @endphp
                <tr class="align-top"><td class="whitespace-nowrap px-4 py-3 text-gray-700 dark:text-gray-300">{{ $row['changed_at'] ?? '—' }}</td><td class="px-3 py-3">{{ $row['user_email'] ?? '—' }}</td><td class="px-3 py-3 font-medium">{{ $row['change_resource_type'] ?? '—' }}</td><td class="px-3 py-3">{{ $row['operation'] ?? '—' }}</td><td class="px-3 py-3">{{ $row['client_type'] ?? '—' }}</td><td class="max-w-xl px-4 py-3 text-xs text-gray-500">{{ $m ? collect($m)->except(['provider','api_version','collector_layer','provider_fact','derived_rates_stored'])->map(fn($v,$k) => $k.': '.(is_scalar($v)?$v:json_encode($v)))->take(5)->implode(' · ') : ($row['change_resource_name'] ?? '—') }}</td></tr>
            @empty <tr><td colspan="6" class="px-4 py-10 text-center text-gray-400">{{ $isTr ? 'Toplanmış Change Event kaydı yok.' : 'No collected Change Event records.' }}</td></tr> @endforelse
        </tbody></table></div>
    </section>
</div>
