@php
    $isTr = app()->getLocale() === 'tr';
    $currency = $professional['currency'] ?? '';
    $groups = collect(data_get($professional, 'pmax.asset_groups', []));
    $assets = collect(data_get($professional, 'pmax.assets', []));
@endphp
<div class="space-y-4">
    <div><h2 class="text-lg font-semibold text-gray-900 dark:text-white">Performance Max</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ $isTr ? 'Asset group ve asset seviyesinde provider-backed PMax görünümü.' : 'Provider-backed Performance Max view across asset groups and assets.' }}</p></div>
    <section class="overflow-hidden rounded-xl bg-white ring-1 ring-inset ring-gray-200 dark:bg-gray-900 dark:ring-gray-800">
        <div class="border-b border-gray-100 px-4 py-3 dark:border-gray-800"><h3 class="font-semibold text-gray-900 dark:text-white">Asset Groups</h3></div>
        <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-xs text-gray-500 dark:bg-white/[0.02]"><tr><th class="px-4 py-2 text-left">Campaign</th><th class="px-3 py-2 text-left">Asset Group</th><th class="px-3 py-2 text-left">Name</th><th class="px-4 py-2 text-left">Status</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@forelse($groups as $row)<tr><td class="px-4 py-2">{{ $row['campaign_id'] ?? '—' }}</td><td class="px-3 py-2">{{ $row['asset_group_id'] ?? '—' }}</td><td class="px-3 py-2 font-medium">{{ $row['name'] ?? '—' }}</td><td class="px-4 py-2">{{ $row['status'] ?? '—' }}</td></tr>@empty<tr><td colspan="4" class="px-4 py-8 text-center text-gray-400">{{ $isTr ? 'PMax asset group verisi yok.' : 'No PMax asset group data.' }}</td></tr>@endforelse</tbody></table></div>
    </section>
    <section class="overflow-hidden rounded-xl bg-white ring-1 ring-inset ring-gray-200 dark:bg-gray-900 dark:ring-gray-800">
        <div class="border-b border-gray-100 px-4 py-3 dark:border-gray-800"><h3 class="font-semibold text-gray-900 dark:text-white">{{ $isTr ? 'Asset performansı' : 'Asset performance' }}</h3></div>
        <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-xs text-gray-500 dark:bg-white/[0.02]"><tr><th class="px-4 py-2 text-left">Asset</th><th class="px-3 py-2 text-left">Field type</th><th class="px-3 py-2 text-right">{{ $isTr ? 'Harcama' : 'Spend' }}</th><th class="px-3 py-2 text-right">Conv.</th><th class="px-3 py-2 text-right">CPA</th><th class="px-4 py-2 text-right">ROAS</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@forelse($assets as $row)<tr><td class="px-4 py-2 font-medium">{{ $row['asset_id'] ?? '—' }}</td><td class="px-3 py-2">{{ $row['field_type'] ?? '—' }}</td><td class="px-3 py-2 text-right">{{ number_format((float)($row['cost'] ?? 0),2,',','.') }} {{ $currency }}</td><td class="px-3 py-2 text-right">{{ number_format((float)($row['conversions'] ?? 0),2,',','.') }}</td><td class="px-3 py-2 text-right">{{ is_numeric($row['cpa'] ?? null) ? number_format((float)$row['cpa'],2,',','.').' '.$currency : '—' }}</td><td class="px-4 py-2 text-right">{{ is_numeric($row['roas'] ?? null) ? number_format((float)$row['roas'],2,',','.').'x' : '—' }}</td></tr>@empty<tr><td colspan="6" class="px-4 py-8 text-center text-gray-400">{{ $isTr ? 'PMax asset performans verisi yok.' : 'No PMax asset performance data.' }}</td></tr>@endforelse</tbody></table></div>
    </section>
    <div class="rounded-xl bg-gray-50 px-4 py-3 text-xs text-gray-500 ring-1 ring-inset ring-gray-200 dark:bg-white/[0.02] dark:ring-gray-800">{{ $isTr ? 'PMax search term verisi ayrı Search Terms datasetinden Arama sekmesine akar; burada yalnız PMax’e özgü asset group/asset katmanı gösterilir.' : 'PMax search-term data flows to the Search workspace from the shared Search Terms dataset; this tab is reserved for PMax-specific asset group/asset facts.' }}</div>
</div>
