@php $isTr = app()->getLocale() === 'tr'; $currency = $professional['currency'] ?? ''; $rows = collect($professional['shopping'] ?? []); @endphp
<div class="space-y-4">
    <div><h2 class="text-lg font-semibold text-gray-900 dark:text-white">Shopping</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ $isTr ? 'Ürün bazında harcama, dönüşüm ve dönüşüm değeri. Ürün kimliği provider product key olarak korunur.' : 'Product-level spend, conversions and conversion value. Product identity is preserved with the provider product key.' }}</p></div>
    <section class="overflow-hidden rounded-xl bg-white ring-1 ring-inset ring-gray-200 dark:bg-gray-900 dark:ring-gray-800">
        <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-xs text-gray-500 dark:bg-white/[0.02]"><tr><th class="px-4 py-2 text-left">Product key</th><th class="px-3 py-2 text-right">Impr.</th><th class="px-3 py-2 text-right">Clicks</th><th class="px-3 py-2 text-right">{{ $isTr ? 'Harcama' : 'Spend' }}</th><th class="px-3 py-2 text-right">Conv.</th><th class="px-3 py-2 text-right">CPA</th><th class="px-4 py-2 text-right">ROAS</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">
            @forelse($rows as $row)<tr><td class="px-4 py-2 font-mono text-xs">{{ $row['product_key'] ?? '—' }}</td><td class="px-3 py-2 text-right">{{ number_format((int)($row['impressions'] ?? 0),0,',','.') }}</td><td class="px-3 py-2 text-right">{{ number_format((int)($row['clicks'] ?? 0),0,',','.') }}</td><td class="px-3 py-2 text-right">{{ number_format((float)($row['cost'] ?? 0),2,',','.') }} {{ $currency }}</td><td class="px-3 py-2 text-right">{{ number_format((float)($row['conversions'] ?? 0),2,',','.') }}</td><td class="px-3 py-2 text-right">{{ is_numeric($row['cpa'] ?? null) ? number_format((float)$row['cpa'],2,',','.').' '.$currency : '—' }}</td><td class="px-4 py-2 text-right">{{ is_numeric($row['roas'] ?? null) ? number_format((float)$row['roas'],2,',','.').'x' : '—' }}</td></tr>@empty<tr><td colspan="7" class="px-4 py-10 text-center text-gray-400">{{ $isTr ? 'Shopping ürün verisi yok.' : 'No Shopping product data.' }}</td></tr>@endforelse
        </tbody></table></div>
    </section>
</div>
