@php $isTr = app()->getLocale() === 'tr'; $currency = $professional['currency'] ?? ''; $rows = collect($professional['video'] ?? []); @endphp
<div class="space-y-4">
    <div><h2 class="text-lg font-semibold text-gray-900 dark:text-white">Video</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ $isTr ? 'Video reklam performansı ve izlenme derinliği.' : 'Video ad performance and viewing depth.' }}</p></div>
    <section class="overflow-hidden rounded-xl bg-white ring-1 ring-inset ring-gray-200 dark:bg-gray-900 dark:ring-gray-800">
        <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-xs text-gray-500 dark:bg-white/[0.02]"><tr><th class="px-4 py-2 text-left">Video</th><th class="px-3 py-2 text-left">Format</th><th class="px-3 py-2 text-right">Views</th><th class="px-3 py-2 text-right">{{ $isTr ? 'Harcama' : 'Spend' }}</th><th class="px-3 py-2 text-right">25%</th><th class="px-3 py-2 text-right">50%</th><th class="px-3 py-2 text-right">75%</th><th class="px-4 py-2 text-right">100%</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">
            @forelse($rows as $row)<tr><td class="px-4 py-2 font-medium">{{ $row['video_id'] ?? '—' }}</td><td class="px-3 py-2">{{ $row['ad_format_type'] ?? '—' }}</td><td class="px-3 py-2 text-right">{{ number_format((int)($row['video_views'] ?? 0),0,',','.') }}</td><td class="px-3 py-2 text-right">{{ number_format((float)($row['cost'] ?? 0),2,',','.') }} {{ $currency }}</td><td class="px-3 py-2 text-right">{{ is_numeric($row['p25'] ?? null) ? number_format((float)$row['p25']*100,1,',','.').'%' : '—' }}</td><td class="px-3 py-2 text-right">{{ is_numeric($row['p50'] ?? null) ? number_format((float)$row['p50']*100,1,',','.').'%' : '—' }}</td><td class="px-3 py-2 text-right">{{ is_numeric($row['p75'] ?? null) ? number_format((float)$row['p75']*100,1,',','.').'%' : '—' }}</td><td class="px-4 py-2 text-right">{{ is_numeric($row['p100'] ?? null) ? number_format((float)$row['p100']*100,1,',','.').'%' : '—' }}</td></tr>@empty<tr><td colspan="8" class="px-4 py-10 text-center text-gray-400">{{ $isTr ? 'Video performans verisi yok.' : 'No video performance data.' }}</td></tr>@endforelse
        </tbody></table></div>
    </section>
</div>
