<?php

/**
 * Website Intelligence V1 runtime amendments.
 *
 * The public crawler is provider-neutral and represents what search engines/users can
 * observe. WordPress is an optional deep capability on the same Website Digital Asset.
 */

$column = static fn (string $name, string $type, bool $nullable = true, string $role = 'dimension', mixed $default = null): array => array_filter([
    'name' => $name,
    'type' => $type,
    'nullable' => $nullable,
    'role' => $role,
    'default' => $default,
], static fn (mixed $value, string $key): bool => $key !== 'default' || $value !== null, ARRAY_FILTER_USE_BOTH);

$provenance = [
    $column('contract_version', 'integer', false, 'provenance'),
    $column('last_collection_run_id', 'bigint', true, 'provenance'),
    $column('last_dataset_run_id', 'bigint', true, 'provenance'),
    $column('first_collected_at', 'timestamptz', false, 'provenance'),
    $column('last_collected_at', 'timestamptz', false, 'provenance'),
    $column('source_timezone', 'text', true, 'provenance'),
    $column('record_fingerprint', 'char(64)', false, 'provenance'),
    $column('metadata', 'json', true, 'extension'),
];

return [
    'registry_overlay' => [
        'overlay_id' => 'WEBSITE_INTELLIGENCE_V1',
        'request_families' => [
            [
                'id' => 'WEB_RF_WP_REST',
                'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
                'capability_endpoint_resource' => 'Authenticated MoxDOP WordPress Connector read-only inventory',
                'requirement_ids' => [
                    'WEB_CONTENT_META',
                    'WEB_CONTENT_TITLE',
                    'WEB_CONTENT_INVENTORY',
                    'WEB_HEALTH_WP_UPDATES',
                    'WEB_INFRA_CMS',
                    'WEB_OVERVIEW_INVENTORY',
                ],
                'dimensions_fields' => [],
                'metrics' => [],
                'segments_breakdowns' => [],
                'date_behavior' => 'CMS object dates plus connector observed_at',
                'pagination_streaming' => 'section and page checkpoint',
                'sync_async_recommendation' => 'sync',
                'volume_risk' => 'MEDIUM',
                'cost_class' => null,
                'paid_call' => false,
                'compatibility_status' => 'VERIFIED_IN_CONNECTOR_V1',
                'eligibility' => ['paired Website-scoped connector'],
                'notes' => 'Read-only authenticated CMS inventory; Public Discovery remains required for published output.',
                'status' => 'COLLECTION_READY',
            ],
        ],
        'datasets' => [
            [
                'id' => 'website_html_snapshot',
                'provider_or_source' => 'WEBSITE_DIRECT',
                'description' => 'Versioned final public HTML observations with content-addressed private artifacts',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'url', 'observed_at'],
                'primary_dimensions' => ['requested_url', 'final_url', 'status_code', 'content_type', 'html_hash', 'change_state'],
                'base_metrics' => ['html_bytes'],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'on_change', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'crawl', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'HIGH',
                'consumer_requirement_ids' => ['WEB_CONTENT_BODY', 'WEB_CONTENT_DIRECTORY'],
                'cross_asset_keys' => ['website_url'],
                'provenance' => 'PUBLIC_HTTP_HTML',
                'completeness_limitations' => 'Only publicly reachable HTML is retained. Draft/private CMS content has no public final HTML.',
                'status' => 'COLLECTION_READY',
            ],
            [
                'id' => 'website_cms_site_snapshot',
                'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
                'description' => 'Authenticated WordPress/PHP/site runtime facts',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'cms', 'site_key', 'observed_at'],
                'primary_dimensions' => ['wordpress_version', 'php_version', 'active_theme', 'rest_state', 'cron_state'],
                'base_metrics' => [],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'current', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'connector', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'TINY',
                'consumer_requirement_ids' => ['WEB_HEALTH_WP_UPDATES', 'WEB_INFRA_CMS'],
                'cross_asset_keys' => [],
                'provenance' => 'CMS_CONFIGURED',
                'completeness_limitations' => 'Does not prove external HTTP, TLS, DNS, CDN or published HTML behavior.',
                'status' => 'COLLECTION_READY',
            ],
            [
                'id' => 'website_cms_object_snapshot',
                'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
                'description' => 'Authenticated WordPress content and media inventory',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'],
                'primary_dimensions' => ['permalink', 'status', 'slug', 'published_at', 'modified_at'],
                'base_metrics' => [],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'current', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'connector', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'MEDIUM',
                'consumer_requirement_ids' => ['WEB_CONTENT_INVENTORY', 'WEB_OVERVIEW_INVENTORY'],
                'cross_asset_keys' => ['website_url'],
                'provenance' => 'CMS_CONFIGURED',
                'completeness_limitations' => 'Full content is retained in private compressed raw ingestion; normalized rows retain inventory and hashes.',
                'status' => 'COLLECTION_READY',
            ],
            [
                'id' => 'website_cms_extension_snapshot',
                'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
                'description' => 'Authenticated WordPress plugin and theme inventory',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'cms', 'extension_type', 'extension_id', 'observed_at'],
                'primary_dimensions' => ['name', 'version', 'status', 'available_version'],
                'base_metrics' => ['update_available'],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'current', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'connector', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'SMALL',
                'consumer_requirement_ids' => ['WEB_HEALTH_WP_UPDATES'],
                'cross_asset_keys' => [],
                'provenance' => 'CMS_CONFIGURED',
                'completeness_limitations' => 'Update state is not a vulnerability assertion and depends on WordPress update-check freshness.',
                'status' => 'COLLECTION_READY',
            ],
            [
                'id' => 'website_cms_taxonomy_snapshot',
                'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
                'description' => 'Authenticated WordPress taxonomy and language inventory',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'cms', 'taxonomy', 'term_id', 'observed_at'],
                'primary_dimensions' => ['name', 'slug', 'parent_id', 'language'],
                'base_metrics' => ['content_count'],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'current', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'connector', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'SMALL',
                'consumer_requirement_ids' => ['WEB_CONTENT_INVENTORY'],
                'cross_asset_keys' => [],
                'provenance' => 'CMS_CONFIGURED',
                'completeness_limitations' => 'Language is present only when a supported plugin exposes it.',
                'status' => 'COLLECTION_READY',
            ],
            [
                'id' => 'website_cms_seo_snapshot',
                'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
                'description' => 'Allowlisted WordPress SEO plugin configuration fields',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'],
                'primary_dimensions' => ['permalink', 'seo_provider', 'seo_title', 'meta_description', 'canonical_url', 'robots'],
                'base_metrics' => [],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'current', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'connector', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'MEDIUM',
                'consumer_requirement_ids' => ['WEB_CONTENT_META', 'WEB_CONTENT_TITLE'],
                'cross_asset_keys' => ['website_url'],
                'provenance' => 'CMS_CONFIGURED',
                'completeness_limitations' => 'Configured fields do not prove they are emitted in published HTML; Public Discovery is required for parity.',
                'status' => 'COLLECTION_READY',
            ],
        ],
    ],

    // Used by the integrity registry runtime overlay for datasets introduced here.
    'integrity_request_families' => [
        'website_cms_site_snapshot' => ['WEB_RF_WP_REST'],
        'website_cms_object_snapshot' => ['WEB_RF_WP_REST'],
        'website_cms_extension_snapshot' => ['WEB_RF_WP_REST'],
        'website_cms_taxonomy_snapshot' => ['WEB_RF_WP_REST'],
        'website_cms_seo_snapshot' => ['WEB_RF_WP_REST'],
        'website_html_snapshot' => ['WEB_RF_PUBLIC_CRAWL', 'WEB_RF_HTTP_HTML_DIAGNOSIS'],
        'website_link_edge' => ['WEB_RF_PUBLIC_CRAWL', 'WEB_RF_HTTP_HTML_DIAGNOSIS'],
        'website_crawl_issue_snapshot' => ['WEB_RF_PUBLIC_CRAWL', 'WEB_RF_HTTP_HTML_DIAGNOSIS'],
    ],

    'physical_additions' => [
        'website_html_snapshot' => [
            'table' => 'website_html_snapshot',
            'provider_or_source' => 'WEBSITE_DIRECT',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'url', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'url', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('url', 'text', false, 'identity'),
                $column('requested_url', 'text', true),
                $column('final_url', 'text', true),
                $column('status_code', 'integer', true),
                $column('content_type', 'text', true),
                $column('html_hash', 'char(64)', false, 'identity'),
                $column('previous_html_hash', 'char(64)', true),
                $column('change_state', 'text', false),
                $column('html_bytes', 'bigint', false, 'metric'),
                $column('raw_ingestion_object_id', 'bigint', true, 'extension'),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_cms_site_snapshot' => [
            'table' => 'website_cms_site_snapshot',
            'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'cms', 'site_key', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'cms', 'site_key', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('cms', 'text', false, 'identity'),
                $column('site_key', 'text', false, 'identity'),
                $column('site_url', 'text', false),
                $column('home_url', 'text', true),
                $column('wordpress_version', 'text', true),
                $column('php_version', 'text', true),
                $column('locale', 'text', true),
                $column('timezone', 'text', true),
                $column('active_theme', 'text', true),
                $column('is_multisite', 'boolean', false, 'dimension', false),
                $column('rest_state', 'text', true),
                $column('cron_state', 'text', true),
                $column('site_health_good_count', 'integer', true, 'metric'),
                $column('site_health_recommended_count', 'integer', true, 'metric'),
                $column('site_health_critical_count', 'integer', true, 'metric'),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_cms_object_snapshot' => [
            'table' => 'website_cms_object_snapshot',
            'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('cms', 'text', false, 'identity'),
                $column('object_type', 'text', false, 'identity'),
                $column('object_id', 'text', false, 'identity'),
                $column('status', 'text', true),
                $column('slug', 'text', true),
                $column('permalink', 'text', true),
                $column('title', 'text', true),
                $column('published_at', 'timestamptz', true),
                $column('modified_at', 'timestamptz', true),
                $column('parent_id', 'text', true),
                $column('template', 'text', true),
                $column('featured_media_id', 'text', true),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_cms_extension_snapshot' => [
            'table' => 'website_cms_extension_snapshot',
            'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'cms', 'extension_type', 'extension_id', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'cms', 'extension_type', 'extension_id', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('cms', 'text', false, 'identity'),
                $column('extension_type', 'text', false, 'identity'),
                $column('extension_id', 'text', false, 'identity'),
                $column('name', 'text', true),
                $column('version', 'text', true),
                $column('status', 'text', true),
                $column('update_available', 'boolean', false, 'dimension', false),
                $column('available_version', 'text', true),
                $column('auto_update', 'boolean', true),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_cms_taxonomy_snapshot' => [
            'table' => 'website_cms_taxonomy_snapshot',
            'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'cms', 'taxonomy', 'term_id', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'cms', 'taxonomy', 'term_id', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('cms', 'text', false, 'identity'),
                $column('taxonomy', 'text', false, 'identity'),
                $column('term_id', 'text', false, 'identity'),
                $column('name', 'text', true),
                $column('slug', 'text', true),
                $column('parent_id', 'text', true),
                $column('content_count', 'integer', true, 'metric'),
                $column('language', 'text', true),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_cms_seo_snapshot' => [
            'table' => 'website_cms_seo_snapshot',
            'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('cms', 'text', false, 'identity'),
                $column('object_type', 'text', false, 'identity'),
                $column('object_id', 'text', false, 'identity'),
                $column('permalink', 'text', true),
                $column('seo_provider', 'text', true),
                $column('seo_title', 'text', true),
                $column('meta_description', 'text', true),
                $column('canonical_url', 'text', true),
                $column('robots', 'text', true),
                $column('language', 'text', true),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_link_edge' => [
            'table' => 'website_link_edge',
            'provider_or_source' => 'WEBSITE_DIRECT',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'edge_key', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'edge_key', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('edge_key', 'char(64)', false, 'identity'),
                $column('source_url', 'text', false, 'identity'),
                $column('target_url', 'text', false),
                $column('normalized_target_url', 'text', false),
                $column('is_internal', 'boolean', false, 'dimension', false),
                $column('anchor_text', 'text', true),
                $column('rel', 'text', true),
                $column('nofollow', 'boolean', false, 'dimension', false),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_crawl_issue_snapshot' => [
            'table' => 'website_crawl_issue_snapshot',
            'provider_or_source' => 'WEBSITE_DIRECT',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'url', 'issue_code', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'url', 'issue_code', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('url', 'text', false, 'identity'),
                $column('issue_code', 'text', false, 'identity'),
                $column('severity', 'text', false),
                $column('message', 'text', false),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],
    ],
];
