<?php

/**
 * Website Intelligence V1 runtime amendments.
 *
 * The public crawler is provider-neutral and represents what search engines/users can
 * observe. WordPress is an optional deep capability on the same Website Digital Asset.
 */
$column = static fn (string $name, string $type, bool $nullable = true, string $role = 'dimension', mixed $default = null): array => array_filter([
    'name' => $name,
    'type' => $type,
    'nullable' => $nullable,
    'role' => $role,
    'default' => $default,
], static fn (mixed $value, string $key): bool => $key !== 'default' || $value !== null, ARRAY_FILTER_USE_BOTH);

$provenance = [
    $column('contract_version', 'integer', false, 'provenance'),
    $column('last_collection_run_id', 'bigint', true, 'provenance'),
    $column('last_dataset_run_id', 'bigint', true, 'provenance'),
    $column('first_collected_at', 'timestamptz', false, 'provenance'),
    $column('last_collected_at', 'timestamptz', false, 'provenance'),
    $column('source_timezone', 'text', true, 'provenance'),
    $column('record_fingerprint', 'char(64)', false, 'provenance'),
    $column('metadata', 'json', true, 'extension'),
];

/*
 * Freshness policies for the datasets this overlay introduces. None of them is scheduled incrementally: the public
 * crawl / HTTP diagnosis refresh the public datasets on demand, the WordPress Connector reconciliation refreshes
 * the CMS datasets. Registered in moxdop-data-freshness.policy_overlays.
 */
$onDemand = static function (string $datasetId, string $source, array $grain, string $reason, int $slaHours = 168): array {
    return [
        'dataset_id' => $datasetId,
        'provider_or_source' => $source,
        'policy_version' => 1,
        'collection_mode' => 'CONTROLLED_ON_DEMAND',
        'incremental_applicable' => false,
        'non_applicable_reason' => $reason,
        'reporting_grain' => $grain,
        'timezone_source' => 'observation_timestamp',
        'current_period_collectable' => false,
        'safe_collection_lag_days' => null,
        'freshness_sla_hours' => $slaHours,
        'expected_refresh_cadence' => 'on_demand',
        'late_data_reprocessing' => [
            'strategy' => 'none',
            'window_days' => null,
            'window_source' => 'not_applicable',
            'overlap_existing_coverage_allowed' => false,
        ],
        'catch_up_policy' => 'not_applicable',
        'max_bounded_incremental_span_days' => null,
        'snapshot_policy' => [
            'freshness_basis' => 'last_successful_collection_at',
            'freshness_sla_hours' => $slaHours,
            'historical_watermark_applicable' => false,
            'reprocessing_applicable' => false,
        ],
        'provider_history_limitation_ref' => null,
        'integrity_dependency' => [
            'integrity_registry_id' => 'MOXDOP_DATA_INTEGRITY_REGISTRY',
            'blocks_trusted_fresh_on_migration_blocking_fail' => true,
        ],
        'contract_refresh_policy' => ['type' => 'on_demand', 'cadence' => 'on_demand'],
        'contract_history_policy' => ['minimum_required' => 'current', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
        'period_non_additive_notes' => null,
        'policy_source' => [
            'data_contract_dataset_id' => $datasetId,
            'integrity_profile' => true,
            'provider_documentation_verified_at' => '2026-09-27',
            'provider_documentation' => [
                'sources' => ['docs/data-contracts/WEBSITE_DATA_CONTRACT_V1.md'],
                'notes' => 'Website Intelligence V1 runtime overlay. Missing remains missing.',
            ],
        ],
    ];
};

$crawlReason = 'Public crawl / HTTP diagnosis observations; refreshed when the site is crawled, not routine incremental.';
$connectorReason = 'WordPress Connector inventory; refreshed by connector sync and reconciliation, not routine incremental.';

return [
    /*
     * "Nazik mod" of the public crawler (WebsiteCrawlPoliteness): small shared hosts must not be overloaded.
     * A few pages at a time per site, a short pause between steps, one step per site across all workers; a site
     * that answers 429 / 502 / 503 / 504, times out or shows the WordPress database error gets 5 → 15 → 60 minute
     * breaks and one page at a time.
     */
    'crawl' => [
        'concurrency' => (int) env('MOXDOP_CRAWL_CONCURRENCY', 2),
        'batch_size' => (int) env('MOXDOP_CRAWL_BATCH_SIZE', 6),
        'min_delay_seconds' => (int) env('MOXDOP_CRAWL_MIN_DELAY_SECONDS', 2),
        'backoff_minutes' => [5, 15, 60],
        'max_backoffs' => 8,
    ],

    'registry_overlay' => [
        'overlay_id' => 'WEBSITE_INTELLIGENCE_V1',
        'request_families' => [
            [
                'id' => 'WEB_RF_WP_REST',
                'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
                'capability_endpoint_resource' => 'Authenticated MoxDOP WordPress Connector read-only inventory',
                'requirement_ids' => [
                    'WEB_CONTENT_META',
                    'WEB_CONTENT_TITLE',
                    'WEB_CONTENT_INVENTORY',
                    'WEB_HEALTH_WP_UPDATES',
                    'WEB_INFRA_CMS',
                    'WEB_OVERVIEW_INVENTORY',
                ],
                'dimensions_fields' => [],
                'metrics' => [],
                'segments_breakdowns' => [],
                'date_behavior' => 'CMS object dates plus connector observed_at',
                'pagination_streaming' => 'section and page checkpoint',
                'sync_async_recommendation' => 'sync',
                'volume_risk' => 'MEDIUM',
                'cost_class' => null,
                'paid_call' => false,
                'compatibility_status' => 'VERIFIED_IN_CONNECTOR_V1',
                'eligibility' => ['paired Website-scoped connector'],
                'notes' => 'Read-only authenticated CMS inventory; Public Discovery remains required for published output.',
                'status' => 'COLLECTION_READY',
            ],
        ],
        'datasets' => [
            [
                'id' => 'website_html_snapshot',
                'provider_or_source' => 'WEBSITE_DIRECT',
                'description' => 'Versioned final public HTML observations with content-addressed private artifacts',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'url', 'observed_at'],
                'primary_dimensions' => ['requested_url', 'final_url', 'status_code', 'content_type', 'html_hash', 'change_state'],
                'base_metrics' => ['html_bytes'],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'on_change', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'crawl', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'HIGH',
                'consumer_requirement_ids' => ['WEB_CONTENT_BODY', 'WEB_CONTENT_DIRECTORY'],
                'cross_asset_keys' => ['website_url'],
                'provenance' => 'PUBLIC_HTTP_HTML',
                'completeness_limitations' => 'Only publicly reachable HTML is retained. Draft/private CMS content has no public final HTML.',
                'status' => 'COLLECTION_READY',
            ],
            [
                'id' => 'website_link_edge',
                'provider_or_source' => 'WEBSITE_DIRECT',
                'description' => 'Links found in public HTML (source page to target URL, anchor, rel, internal/external)',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'edge_key', 'observed_at'],
                'primary_dimensions' => ['source_url', 'target_url', 'normalized_target_url', 'is_internal', 'anchor_text', 'rel', 'nofollow'],
                'base_metrics' => [],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'current', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'crawl', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'HIGH',
                'consumer_requirement_ids' => ['WEB_CONTENT_BODY'],
                'cross_asset_keys' => ['website_url'],
                'provenance' => 'PUBLIC_HTTP_HTML',
                'completeness_limitations' => 'Only links present in crawled, publicly reachable HTML; JavaScript-injected links are not seen.',
                'status' => 'COLLECTION_READY',
            ],
            [
                'id' => 'website_crawl_issue_snapshot',
                'provider_or_source' => 'WEBSITE_DIRECT',
                'description' => 'Technical issues the public crawl found per URL (issue code, severity, message)',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'url', 'issue_code', 'observed_at'],
                'primary_dimensions' => ['url', 'issue_code', 'severity', 'message'],
                'base_metrics' => [],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'current', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'crawl', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'MEDIUM',
                'consumer_requirement_ids' => ['WEB_CONTENT_BODY'],
                'cross_asset_keys' => ['website_url'],
                'provenance' => 'PUBLIC_HTTP_HTML',
                'completeness_limitations' => 'Issues are observations of the last crawl; an issue absent from a partial crawl is not proof it is fixed.',
                'status' => 'COLLECTION_READY',
            ],
            [
                'id' => 'website_cms_site_snapshot',
                'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
                'description' => 'Authenticated WordPress/PHP/site runtime facts',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'cms', 'site_key', 'observed_at'],
                'primary_dimensions' => ['wordpress_version', 'php_version', 'active_theme', 'rest_state', 'cron_state'],
                'base_metrics' => [],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'current', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'connector', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'TINY',
                'consumer_requirement_ids' => ['WEB_HEALTH_WP_UPDATES', 'WEB_INFRA_CMS'],
                'cross_asset_keys' => [],
                'provenance' => 'CMS_CONFIGURED',
                'completeness_limitations' => 'Does not prove external HTTP, TLS, DNS, CDN or published HTML behavior.',
                'status' => 'COLLECTION_READY',
            ],
            [
                'id' => 'website_cms_object_snapshot',
                'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
                'description' => 'Authenticated WordPress content and media inventory',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'],
                'primary_dimensions' => ['permalink', 'status', 'slug', 'published_at', 'modified_at'],
                'base_metrics' => [],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'current', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'connector', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'MEDIUM',
                'consumer_requirement_ids' => ['WEB_CONTENT_INVENTORY', 'WEB_OVERVIEW_INVENTORY'],
                'cross_asset_keys' => ['website_url'],
                'provenance' => 'CMS_CONFIGURED',
                'completeness_limitations' => 'Full content is retained in private compressed raw ingestion; normalized rows retain inventory and hashes.',
                'status' => 'COLLECTION_READY',
            ],
            [
                'id' => 'website_cms_extension_snapshot',
                'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
                'description' => 'Authenticated WordPress plugin and theme inventory',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'cms', 'extension_type', 'extension_id', 'observed_at'],
                'primary_dimensions' => ['name', 'version', 'status', 'available_version'],
                'base_metrics' => ['update_available'],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'current', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'connector', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'SMALL',
                'consumer_requirement_ids' => ['WEB_HEALTH_WP_UPDATES'],
                'cross_asset_keys' => [],
                'provenance' => 'CMS_CONFIGURED',
                'completeness_limitations' => 'Update state is not a vulnerability assertion and depends on WordPress update-check freshness.',
                'status' => 'COLLECTION_READY',
            ],
            [
                'id' => 'website_cms_taxonomy_snapshot',
                'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
                'description' => 'Authenticated WordPress taxonomy and language inventory',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'cms', 'taxonomy', 'term_id', 'observed_at'],
                'primary_dimensions' => ['name', 'slug', 'parent_id', 'language'],
                'base_metrics' => ['content_count'],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'current', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'connector', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'SMALL',
                'consumer_requirement_ids' => ['WEB_CONTENT_INVENTORY'],
                'cross_asset_keys' => [],
                'provenance' => 'CMS_CONFIGURED',
                'completeness_limitations' => 'Language is present only when a supported plugin exposes it.',
                'status' => 'COLLECTION_READY',
            ],
            [
                'id' => 'website_cms_seo_snapshot',
                'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
                'description' => 'Allowlisted WordPress SEO plugin configuration fields',
                'storage_class' => 'NORMALIZED_SNAPSHOT',
                'grain' => ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'],
                'primary_dimensions' => ['permalink', 'seo_provider', 'seo_title', 'meta_description', 'canonical_url', 'robots'],
                'base_metrics' => [],
                'snapshot_or_timeseries' => 'snapshot',
                'partition_candidate' => null,
                'history_policy' => ['minimum_required' => 'current', 'recommended_initial_backfill' => 'current', 'decision_required' => false],
                'refresh_policy' => ['type' => 'connector', 'cadence' => 'on_sync'],
                'estimated_volume_class' => 'MEDIUM',
                'consumer_requirement_ids' => ['WEB_CONTENT_META', 'WEB_CONTENT_TITLE'],
                'cross_asset_keys' => ['website_url'],
                'provenance' => 'CMS_CONFIGURED',
                'completeness_limitations' => 'Configured fields do not prove they are emitted in published HTML; Public Discovery is required for parity.',
                'status' => 'COLLECTION_READY',
            ],
        ],
    ],

    // Used by the integrity registry runtime overlay for datasets introduced here.
    'integrity_request_families' => [
        'website_cms_site_snapshot' => ['WEB_RF_WP_REST'],
        'website_cms_object_snapshot' => ['WEB_RF_WP_REST'],
        'website_cms_extension_snapshot' => ['WEB_RF_WP_REST'],
        'website_cms_taxonomy_snapshot' => ['WEB_RF_WP_REST'],
        'website_cms_seo_snapshot' => ['WEB_RF_WP_REST'],
        'website_html_snapshot' => ['WEB_RF_PUBLIC_CRAWL', 'WEB_RF_HTTP_HTML_DIAGNOSIS'],
        'website_link_edge' => ['WEB_RF_PUBLIC_CRAWL', 'WEB_RF_HTTP_HTML_DIAGNOSIS'],
        'website_crawl_issue_snapshot' => ['WEB_RF_PUBLIC_CRAWL', 'WEB_RF_HTTP_HTML_DIAGNOSIS'],
    ],

    'physical_additions' => [
        'website_html_snapshot' => [
            'table' => 'website_html_snapshot',
            'provider_or_source' => 'WEBSITE_DIRECT',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'url', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'url', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('url', 'text', false, 'identity'),
                $column('requested_url', 'text', true),
                $column('final_url', 'text', true),
                $column('status_code', 'integer', true),
                $column('content_type', 'text', true),
                $column('html_hash', 'char(64)', false, 'identity'),
                $column('previous_html_hash', 'char(64)', true),
                $column('change_state', 'text', false),
                $column('html_bytes', 'bigint', false, 'metric'),
                $column('raw_ingestion_object_id', 'bigint', true, 'extension'),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_cms_site_snapshot' => [
            'table' => 'website_cms_site_snapshot',
            'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'cms', 'site_key', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'cms', 'site_key', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('cms', 'text', false, 'identity'),
                $column('site_key', 'text', false, 'identity'),
                $column('site_url', 'text', false),
                $column('home_url', 'text', true),
                $column('wordpress_version', 'text', true),
                $column('php_version', 'text', true),
                $column('locale', 'text', true),
                $column('timezone', 'text', true),
                $column('active_theme', 'text', true),
                $column('is_multisite', 'boolean', false, 'dimension', false),
                $column('rest_state', 'text', true),
                $column('cron_state', 'text', true),
                $column('site_health_good_count', 'integer', true, 'metric'),
                $column('site_health_recommended_count', 'integer', true, 'metric'),
                $column('site_health_critical_count', 'integer', true, 'metric'),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_cms_object_snapshot' => [
            'table' => 'website_cms_object_snapshot',
            'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('cms', 'text', false, 'identity'),
                $column('object_type', 'text', false, 'identity'),
                $column('object_id', 'text', false, 'identity'),
                $column('status', 'text', true),
                $column('slug', 'text', true),
                $column('permalink', 'text', true),
                $column('title', 'text', true),
                $column('published_at', 'timestamptz', true),
                $column('modified_at', 'timestamptz', true),
                $column('parent_id', 'text', true),
                $column('template', 'text', true),
                $column('featured_media_id', 'text', true),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_cms_extension_snapshot' => [
            'table' => 'website_cms_extension_snapshot',
            'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'cms', 'extension_type', 'extension_id', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'cms', 'extension_type', 'extension_id', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('cms', 'text', false, 'identity'),
                $column('extension_type', 'text', false, 'identity'),
                $column('extension_id', 'text', false, 'identity'),
                $column('name', 'text', true),
                $column('version', 'text', true),
                $column('status', 'text', true),
                $column('update_available', 'boolean', false, 'dimension', false),
                $column('available_version', 'text', true),
                $column('auto_update', 'boolean', true),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_cms_taxonomy_snapshot' => [
            'table' => 'website_cms_taxonomy_snapshot',
            'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'cms', 'taxonomy', 'term_id', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'cms', 'taxonomy', 'term_id', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('cms', 'text', false, 'identity'),
                $column('taxonomy', 'text', false, 'identity'),
                $column('term_id', 'text', false, 'identity'),
                $column('name', 'text', true),
                $column('slug', 'text', true),
                $column('parent_id', 'text', true),
                $column('content_count', 'integer', true, 'metric'),
                $column('language', 'text', true),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_cms_seo_snapshot' => [
            'table' => 'website_cms_seo_snapshot',
            'provider_or_source' => 'WORDPRESS_SITE_CONNECTOR',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('cms', 'text', false, 'identity'),
                $column('object_type', 'text', false, 'identity'),
                $column('object_id', 'text', false, 'identity'),
                $column('permalink', 'text', true),
                $column('seo_provider', 'text', true),
                $column('seo_title', 'text', true),
                $column('meta_description', 'text', true),
                $column('canonical_url', 'text', true),
                $column('robots', 'text', true),
                $column('language', 'text', true),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_link_edge' => [
            'table' => 'website_link_edge',
            'provider_or_source' => 'WEBSITE_DIRECT',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'edge_key', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'edge_key', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('edge_key', 'char(64)', false, 'identity'),
                $column('source_url', 'text', false, 'identity'),
                $column('target_url', 'text', false),
                $column('normalized_target_url', 'text', false),
                $column('is_internal', 'boolean', false, 'dimension', false),
                $column('anchor_text', 'text', true),
                $column('rel', 'text', true),
                $column('nofollow', 'boolean', false, 'dimension', false),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],

        'website_crawl_issue_snapshot' => [
            'table' => 'website_crawl_issue_snapshot',
            'provider_or_source' => 'WEBSITE_DIRECT',
            'storage_class' => 'NORMALIZED_SNAPSHOT',
            'write_mode' => 'UPSERT_CURRENT_STATE',
            'partition_strategy' => 'NONE',
            'partition_column' => null,
            'grain' => ['digital_asset_id', 'url', 'issue_code', 'observed_at'],
            'natural_key' => ['digital_asset_id', 'url', 'issue_code', 'observed_at'],
            'columns' => [
                $column('digital_asset_id', 'bigint', false, 'scope'),
                $column('external_resource_id', 'bigint', true, 'scope'),
                $column('url', 'text', false, 'identity'),
                $column('issue_code', 'text', false, 'identity'),
                $column('severity', 'text', false),
                $column('message', 'text', false),
                $column('observed_at', 'timestamptz', false, 'identity'),
                ...$provenance,
            ],
        ],
    ],
    'freshness_overlay' => [
        'overlay_id' => 'WEBSITE_INTELLIGENCE_FRESHNESS_V1',
        'dataset_policies' => [
            $onDemand('website_html_snapshot', 'WEBSITE_DIRECT', ['digital_asset_id', 'url', 'observed_at'], $crawlReason),
            $onDemand('website_content_stats', 'WEBSITE_DIRECT', ['url', 'observed_at'], $crawlReason),
            $onDemand('website_link_edge', 'WEBSITE_DIRECT', ['digital_asset_id', 'edge_key', 'observed_at'], $crawlReason),
            $onDemand('website_crawl_issue_snapshot', 'WEBSITE_DIRECT', ['digital_asset_id', 'url', 'issue_code', 'observed_at'], $crawlReason),
            $onDemand('website_cms_site_snapshot', 'WORDPRESS_SITE_CONNECTOR', ['digital_asset_id', 'cms', 'site_key', 'observed_at'], $connectorReason),
            $onDemand('website_cms_object_snapshot', 'WORDPRESS_SITE_CONNECTOR', ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'], $connectorReason),
            $onDemand('website_cms_extension_snapshot', 'WORDPRESS_SITE_CONNECTOR', ['digital_asset_id', 'cms', 'extension_type', 'extension_id', 'observed_at'], $connectorReason),
            $onDemand('website_cms_taxonomy_snapshot', 'WORDPRESS_SITE_CONNECTOR', ['digital_asset_id', 'cms', 'taxonomy', 'term_id', 'observed_at'], $connectorReason),
            $onDemand('website_cms_seo_snapshot', 'WORDPRESS_SITE_CONNECTOR', ['digital_asset_id', 'cms', 'object_type', 'object_id', 'observed_at'], $connectorReason),
        ],
    ],
];
