@php
    $isTr = app()->getLocale() === 'tr';
    $campaigns = $professional['campaigns'] ?? [];
    $adsets = $professional['adsets'] ?? [];
    $ads = $professional['ads'] ?? [];
    $inventory = $professional['campaign_inventory'] ?? ['total' => count($campaigns), 'with_period_activity' => count($campaigns), 'without_period_activity' => 0];
@endphp

<section class="space-y-5" x-data="{ level: 'campaigns' }">
    <div class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div>
            <p class="text-xs font-semibold uppercase tracking-[0.14em] text-gray-400">{{ $isTr ? 'Kampanyalar ve Reklamlar' : 'Campaigns and Ads' }}</p>
            <h2 class="mt-1 text-2xl font-bold text-gray-900 dark:text-white">{{ $isTr ? 'Hangi kampanya ne kadar harcadı ve ne üretti?' : 'What did each campaign spend and produce?' }}</h2>
            <p class="mt-1 max-w-3xl text-sm text-gray-500 dark:text-gray-400">{{ $isTr ? 'Hesaptaki tüm kampanyalar listelenir. Seçili dönemde çalışmayan kampanyalar da kaybolmaz; harcama ve performansları boş/0 görünür.' : 'All campaigns in the account are listed, including campaigns without activity in the selected period.' }}</p>
            <p class="mt-2 text-xs font-medium text-gray-400">{{ $isTr ? 'Toplam '.number_format((int)$inventory['total']).' kampanya · '.number_format((int)$inventory['with_period_activity']).' tanesinde seçili dönemde aktivite var' : number_format((int)$inventory['total']).' campaigns total · '.number_format((int)$inventory['with_period_activity']).' active in period' }}</p>
        </div>
        <div class="inline-flex w-fit rounded-xl bg-gray-100 p-1 dark:bg-white/[0.05]">
            <button type="button" @click="level='campaigns'" :class="level==='campaigns' ? 'bg-white text-gray-900 shadow-sm dark:bg-gray-800 dark:text-white' : 'text-gray-500 dark:text-gray-400'" class="rounded-lg px-3 py-2 text-sm font-semibold">{{ $isTr ? 'Kampanyalar' : 'Campaigns' }} <span class="ml-1 text-xs opacity-60">{{ count($campaigns) }}</span></button>
            <button type="button" @click="level='adsets'" :class="level==='adsets' ? 'bg-white text-gray-900 shadow-sm dark:bg-gray-800 dark:text-white' : 'text-gray-500 dark:text-gray-400'" class="rounded-lg px-3 py-2 text-sm font-semibold">{{ $isTr ? 'Reklam Setleri' : 'Ad Sets' }} <span class="ml-1 text-xs opacity-60">{{ count($adsets) }}</span></button>
            <button type="button" @click="level='ads'" :class="level==='ads' ? 'bg-white text-gray-900 shadow-sm dark:bg-gray-800 dark:text-white' : 'text-gray-500 dark:text-gray-400'" class="rounded-lg px-3 py-2 text-sm font-semibold">{{ $isTr ? 'Reklamlar' : 'Ads' }} <span class="ml-1 text-xs opacity-60">{{ count($ads) }}</span></button>
        </div>
    </div>

    <article class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900">
        <div class="flex flex-col gap-2 border-b border-gray-100 px-5 py-4 dark:border-gray-800 sm:flex-row sm:items-center sm:justify-between">
            <div><h3 class="font-bold text-gray-900 dark:text-white" x-text="level === 'campaigns' ? '{{ $isTr ? 'Kampanyalar' : 'Campaigns' }}' : (level === 'adsets' ? '{{ $isTr ? 'Reklam Setleri' : 'Ad Sets' }}' : '{{ $isTr ? 'Reklamlar' : 'Ads' }}')"></h3><p class="mt-0.5 text-xs text-gray-400">{{ $isTr ? 'Meta’nın ölçtüğü sonuç türleri ilgili satırda ayrıca gösterilir; farklı sonuçlar tek sayıda birleştirilmez.' : 'Meta-observed action types are shown per entity and never collapsed into one generic result.' }}</p></div>
            <span class="text-xs font-medium text-gray-400">{{ $professional['period_start'] ?? '—' }} → {{ $professional['period_end'] ?? '—' }}</span>
        </div>

        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-100 text-left dark:divide-gray-800">
                <thead class="bg-gray-50/80 dark:bg-white/[0.02]"><tr class="text-[11px] font-semibold uppercase tracking-wide text-gray-400"><th class="px-5 py-3">{{ $isTr ? 'Ad' : 'Name' }}</th><th class="px-4 py-3">{{ $isTr ? 'Bağlam' : 'Context' }}</th><th class="px-4 py-3">{{ $isTr ? 'Durum' : 'Status' }}</th><th class="px-4 py-3 text-right">{{ $isTr ? 'Harcama' : 'Spend' }}</th><th class="px-4 py-3 text-right">{{ $isTr ? 'Tıklama Oranı' : 'Click Rate' }}<span class="ml-1 normal-case text-gray-300">(CTR)</span></th><th class="px-4 py-3 text-right">{{ $isTr ? 'Tıklama Maliyeti' : 'Click Cost' }}<span class="ml-1 normal-case text-gray-300">(CPC)</span></th><th class="px-5 py-3 min-w-[220px]">{{ $isTr ? 'Ölçülen Sonuçlar' : 'Observed Outcomes' }}</th></tr></thead>

                <tbody x-show="level === 'campaigns'" class="divide-y divide-gray-100 dark:divide-gray-800">
                    @forelse ($campaigns as $row)
                        <tr class="hover:bg-gray-50/70 dark:hover:bg-white/[0.02]"><td class="max-w-xs px-5 py-3.5"><p class="truncate text-sm font-semibold text-gray-800 dark:text-gray-200">{{ $row['name'] }}</p><p class="mt-0.5 text-[11px] text-gray-400">ID {{ $row['id'] }} @if(!($row['has_period_activity'] ?? true)) · {{ $isTr ? 'Bu dönemde aktivite yok' : 'No activity in period' }} @endif</p></td><td class="px-4 py-3.5 text-xs text-gray-500 dark:text-gray-400">{{ $row['objective'] ? str_replace('_', ' ', $row['objective']) : '—' }}</td><td class="px-4 py-3.5"><span class="rounded-full bg-gray-100 px-2 py-1 text-xs font-semibold text-gray-600 dark:bg-white/[0.05] dark:text-gray-300">{{ $row['effective_status'] ?? $row['status'] }}</span></td><td class="px-4 py-3.5 text-right text-sm font-semibold tabular-nums">{{ $row['spend_display'] }}</td><td class="px-4 py-3.5 text-right text-sm tabular-nums">{{ $row['ctr'] !== null ? number_format($row['ctr'], 2).'%' : '—' }}</td><td class="px-4 py-3.5 text-right text-sm tabular-nums">{{ $row['cpc'] !== null ? ($row['currency'].' '.number_format($row['cpc'], 2)) : '—' }}</td><td class="px-5 py-3.5">@forelse(array_slice($row['actions'] ?? [],0,2) as $action)<div class="flex justify-between gap-3 text-xs"><span class="truncate text-gray-600 dark:text-gray-300">{{ $isTr ? $action['label_tr'] : $action['label_en'] }}</span><strong class="tabular-nums text-gray-900 dark:text-white">{{ number_format((float)$action['value'],2) }}</strong></div>@empty<span class="text-xs text-gray-300">—</span>@endforelse</td></tr>
                    @empty<tr><td colspan="7" class="px-5 py-12 text-center text-sm text-gray-400">{{ $isTr ? 'Kampanya envanteri yok.' : 'No campaign inventory.' }}</td></tr>@endforelse
                </tbody>

                <tbody x-show="level === 'adsets'" x-cloak class="divide-y divide-gray-100 dark:divide-gray-800">
                    @forelse ($adsets as $row)
                        <tr class="hover:bg-gray-50/70 dark:hover:bg-white/[0.02]"><td class="max-w-xs px-5 py-3.5"><p class="truncate text-sm font-semibold text-gray-800 dark:text-gray-200">{{ $row['name'] }}</p><p class="mt-0.5 text-[11px] text-gray-400">ID {{ $row['id'] }}</p></td><td class="max-w-xs px-4 py-3.5"><p class="truncate text-xs font-medium text-gray-600 dark:text-gray-300">{{ $row['campaign_name'] ?? '—' }}</p><p class="mt-0.5 text-[11px] text-gray-400">{{ $isTr ? 'Optimizasyon: ' : 'Optimization: ' }}{{ $row['optimization_goal'] ? str_replace('_', ' ', $row['optimization_goal']) : '—' }} @if($row['destination_type']) · {{ $isTr ? 'Hedef: ' : 'Destination: ' }}{{ str_replace('_',' ',$row['destination_type']) }} @endif</p></td><td class="px-4 py-3.5"><span class="rounded-full bg-gray-100 px-2 py-1 text-xs font-semibold text-gray-600 dark:bg-white/[0.05] dark:text-gray-300">{{ $row['effective_status'] ?? $row['status'] }}</span></td><td class="px-4 py-3.5 text-right text-sm font-semibold tabular-nums">{{ $row['spend_display'] }}</td><td class="px-4 py-3.5 text-right text-sm tabular-nums">{{ $row['ctr'] !== null ? number_format($row['ctr'],2).'%' : '—' }}</td><td class="px-4 py-3.5 text-right text-sm tabular-nums">{{ $row['cpc'] !== null ? ($row['currency'].' '.number_format($row['cpc'],2)) : '—' }}</td><td class="px-5 py-3.5">@forelse(array_slice($row['actions'] ?? [],0,2) as $action)<div class="flex justify-between gap-3 text-xs"><span class="truncate text-gray-600 dark:text-gray-300">{{ $isTr ? $action['label_tr'] : $action['label_en'] }}</span><strong class="tabular-nums">{{ number_format((float)$action['value'],2) }}</strong></div>@empty<span class="text-xs text-gray-300">—</span>@endforelse</td></tr>
                    @empty<tr><td colspan="7" class="px-5 py-12 text-center text-sm text-gray-400">{{ $isTr ? 'Reklam seti verisi yok.' : 'No ad-set data.' }}</td></tr>@endforelse
                </tbody>

                <tbody x-show="level === 'ads'" x-cloak class="divide-y divide-gray-100 dark:divide-gray-800">
                    @forelse ($ads as $row)
                        <tr class="hover:bg-gray-50/70 dark:hover:bg-white/[0.02]"><td class="max-w-xs px-5 py-3.5"><p class="truncate text-sm font-semibold text-gray-800 dark:text-gray-200">{{ $row['name'] }}</p><p class="mt-0.5 text-[11px] text-gray-400">ID {{ $row['id'] }}{{ $row['creative_id'] ? ' · Kreatif '.$row['creative_id'] : '' }}</p></td><td class="max-w-xs px-4 py-3.5"><p class="truncate text-xs font-medium text-gray-600 dark:text-gray-300">{{ $row['campaign_name'] ?? '—' }}</p><p class="mt-0.5 truncate text-[11px] text-gray-400">{{ $row['adset_name'] ?? '—' }}</p></td><td class="px-4 py-3.5"><span class="rounded-full bg-gray-100 px-2 py-1 text-xs font-semibold text-gray-600 dark:bg-white/[0.05] dark:text-gray-300">{{ $row['effective_status'] ?? $row['status'] }}</span></td><td class="px-4 py-3.5 text-right text-sm font-semibold tabular-nums">{{ $row['spend_display'] }}</td><td class="px-4 py-3.5 text-right text-sm tabular-nums">{{ $row['ctr'] !== null ? number_format($row['ctr'],2).'%' : '—' }}</td><td class="px-4 py-3.5 text-right text-sm tabular-nums">{{ $row['cpc'] !== null ? ($row['currency'].' '.number_format($row['cpc'],2)) : '—' }}</td><td class="px-5 py-3.5">@forelse(array_slice($row['actions'] ?? [],0,2) as $action)<div class="flex justify-between gap-3 text-xs"><span class="truncate text-gray-600 dark:text-gray-300">{{ $isTr ? $action['label_tr'] : $action['label_en'] }}</span><strong class="tabular-nums">{{ number_format((float)$action['value'],2) }}</strong></div>@empty<span class="text-xs text-gray-300">—</span>@endforelse</td></tr>
                    @empty<tr><td colspan="7" class="px-5 py-12 text-center text-sm text-gray-400">{{ $isTr ? 'Reklam verisi yok.' : 'No ad data.' }}</td></tr>@endforelse
                </tbody>
            </table>
        </div>
    </article>

    <div class="rounded-xl border border-blue-200 bg-blue-50/60 px-4 py-3 text-xs leading-5 text-blue-800 dark:border-blue-500/20 dark:bg-blue-500/[0.06] dark:text-blue-300">{{ $isTr ? 'Tıklama Oranı (CTR), Tıklama Başına Maliyet (CPC) gibi teknik kısaltmalar uzmanlar için korunur; ana başlıklarda anlaşılır Türkçe kullanılır. Meta’nın farklı action türleri tek bir “Sonuç” sayısına dönüştürülmez.' : 'Technical abbreviations remain available for experts while primary labels stay readable. Different Meta action types are never collapsed into one generic result.' }}</div>
</section>
