<?php

namespace MoxDop\Website\Discovery;

use Illuminate\Http\Client\ConnectionException;
use Illuminate\Http\Client\PendingRequest;
use Illuminate\Http\Client\Pool;
use Illuminate\Http\Client\Response;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Http;
use InvalidArgumentException;
use Throwable;

/**
 * Bounded public HTTP fetcher with SSRF checks on every hop.
 * Does not execute JavaScript. Does not send Authorization headers.
 */
final class PublicHttpFetcher
{
    /** Error code suffix for a WordPress "database connection" error page. */
    public const string DATABASE_ERROR = 'database_connection_error';

    /** @var list<string> */
    public const array DATABASE_ERROR_MARKERS = [
        'Error establishing a database connection',
        'Veritabanı bağlantısı kurulurken hata',
    ];

    /** Footer comments page-cache plugins add to the pages they serve from the cache. */
    public const array CACHE_FOOTER_MARKERS = [
        'This website is like a Rocket' => 'wp_rocket',
        'Cached page generated by WP-Super-Cache' => 'wp_super_cache',
        'Performance optimized by W3 Total Cache' => 'w3_total_cache',
        'WP Fastest Cache file was created' => 'wp_fastest_cache',
        'Cache Enabler by KeyCDN' => 'cache_enabler',
    ];

    public function __construct(
        private readonly PublicUrlSafety $safety = new PublicUrlSafety,
        private readonly PublicUrlNormalizer $normalizer = new PublicUrlNormalizer,
    ) {}

    /**
     * Besides the keys below a result carries `not_modified` (a 304 to a conditional request), `etag`,
     * `last_modified` and `cache` (hit: ?bool, plugin: ?string — whether the site's page cache served it).
     *
     * @param  array{etag?: ?string, last_modified?: ?string}  $validators  sent as If-None-Match / If-Modified-Since
     * @return array{
     *     ok: bool,
     *     requested_url: string,
     *     final_url: ?string,
     *     status_code: ?int,
     *     content_type: ?string,
     *     body: ?string,
     *     bytes: int,
     *     redirect_count: int,
     *     error: ?string
     * }
     */
    public function fetch(string $url, ?int $maxResponseBytes = null, array $validators = []): array
    {
        $maxResponseBytes ??= DiscoveryConfig::MAX_RESPONSE_BYTES;
        $maxResponseBytes = max(1, $maxResponseBytes);
        $current = $this->normalizer->normalizeAbsolute($url);
        if ($current === null) {
            return $this->failure($url, 'invalid_url');
        }

        $redirects = 0;

        for ($hop = 0; $hop <= DiscoveryConfig::MAX_REDIRECTS; $hop++) {
            try {
                $this->safety->assertSafePublicHttpUrl($current);
            } catch (InvalidArgumentException $exception) {
                return $this->failure($url, $exception->getMessage(), $current, $redirects);
            }

            try {
                $response = $this->configure(Http::timeout(DiscoveryConfig::TIMEOUT_SECONDS), $validators, $current)->get($current);
                $host = (string) parse_url($current, PHP_URL_HOST);
                if ($response->status() === 403 && ! self::prefersIpv4($host)) {
                    // Some hosts refuse the server's IPv6 address only: the same request over IPv4.
                    $retry = $this->configure(Http::timeout(DiscoveryConfig::TIMEOUT_SECONDS), $validators, $current, true)->get($current);
                    if ($retry->status() !== 403) {
                        self::preferIpv4($host);
                        $response = $retry;
                    }
                }
            } catch (ConnectionException $exception) {
                return $this->failure($url, 'timeout_or_connection: '.$exception->getMessage(), $current, $redirects);
            } catch (Throwable $exception) {
                return $this->failure($url, 'fetch_error: '.$exception->getMessage(), $current, $redirects);
            }

            $outcome = $this->evaluate($url, $current, $redirects, $response, $maxResponseBytes);
            if (isset($outcome['result'])) {
                return $outcome['result'];
            }
            $current = $outcome['next'];
            $redirects++;
        }

        return $this->failure($url, 'redirect_limit_exceeded', $current, $redirects);
    }

    /**
     * Fetches several URLs concurrently with the same per-hop SSRF check, redirect and byte limits as fetch().
     * Every hop of every URL is checked before it is requested. The result is keyed by the requested URL, in input order.
     *
     * @param  list<string>  $urls
     * @param  array<string, array{etag?: ?string, last_modified?: ?string}>  $validators  per requested URL (conditional requests)
     * @return array<string, array{ok: bool, requested_url: string, final_url: ?string, status_code: ?int, content_type: ?string, body: ?string, bytes: int, redirect_count: int, error: ?string}>
     */
    public function fetchMany(array $urls, ?int $maxResponseBytes = null, int $concurrency = 15, array $validators = []): array
    {
        $maxResponseBytes = max(1, $maxResponseBytes ?? DiscoveryConfig::MAX_RESPONSE_BYTES);
        $urls = array_values(array_unique(array_map('strval', $urls)));
        $results = [];
        /** @var array<string, array{current: string, redirects: int}> $pending */
        $pending = [];
        foreach ($urls as $url) {
            $current = $this->normalizer->normalizeAbsolute($url);
            if ($current === null) {
                $results[$url] = $this->failure($url, 'invalid_url');

                continue;
            }
            $pending[$url] = ['current' => $current, 'redirects' => 0];
        }

        for ($hop = 0; $hop <= DiscoveryConfig::MAX_REDIRECTS && $pending !== []; $hop++) {
            $batch = [];
            foreach ($pending as $url => $state) {
                try {
                    $this->safety->assertSafePublicHttpUrl($state['current']);
                    $batch[] = $url;
                } catch (InvalidArgumentException $exception) {
                    $results[$url] = $this->failure($url, $exception->getMessage(), $state['current'], $state['redirects']);
                    unset($pending[$url]);
                }
            }
            if ($batch === []) {
                break;
            }

            try {
                $responses = Http::pool(function (Pool $pool) use ($batch, $pending, $validators): array {
                    $requests = [];
                    foreach ($batch as $index => $url) {
                        $requests[] = $this->configure($pool->as('u'.$index), $validators[$url] ?? [], $pending[$url]['current'])->get($pending[$url]['current']);
                    }

                    return $requests;
                }, max(1, $concurrency));
            } catch (Throwable $exception) {
                foreach ($batch as $url) {
                    $results[$url] = $this->failure($url, 'fetch_error: '.$exception->getMessage(), $pending[$url]['current'], $pending[$url]['redirects']);
                    unset($pending[$url]);
                }

                break;
            }

            foreach ($batch as $index => $url) {
                $state = $pending[$url];
                $response = $responses['u'.$index] ?? null;
                if (! $response instanceof Response) {
                    $results[$url] = $this->failure(
                        $url,
                        ($response instanceof ConnectionException ? 'timeout_or_connection: ' : 'fetch_error: ')
                            .($response instanceof Throwable ? $response->getMessage() : 'no_response'),
                        $state['current'],
                        $state['redirects'],
                    );
                    unset($pending[$url]);

                    continue;
                }

                $outcome = $this->evaluate($url, $state['current'], $state['redirects'], $response, $maxResponseBytes);
                if (isset($outcome['result'])) {
                    $results[$url] = $outcome['result'];
                    unset($pending[$url]);

                    continue;
                }
                $pending[$url] = ['current' => $outcome['next'], 'redirects' => $state['redirects'] + 1];
            }
        }

        foreach ($pending as $url => $state) {
            $results[$url] = $this->failure($url, 'redirect_limit_exceeded', $state['current'], $state['redirects']);
        }

        $ordered = [];
        foreach ($urls as $url) {
            $ordered[$url] = $results[$url];
        }

        return $ordered;
    }

    /**
     * A request the site's page cache answers like a visitor's: browser-like Accept / Accept-Language /
     * Accept-Encoding (gzip), no cookies, no Cache-Control / Pragma request headers and never a cache-busting
     * query string. Optional If-None-Match / If-Modified-Since turn an unchanged page into a bodyless 304.
     *
     * @param  array{etag?: ?string, last_modified?: ?string}  $validators
     */
    private function configure(PendingRequest $request, array $validators = [], ?string $url = null, bool $ipv4 = false): PendingRequest
    {
        $ipv4 = $ipv4 || ($url !== null && self::prefersIpv4((string) parse_url($url, PHP_URL_HOST)));
        $headers = [
            'User-Agent' => DiscoveryConfig::USER_AGENT,
            'Accept' => DiscoveryConfig::ACCEPT,
            'Accept-Language' => DiscoveryConfig::ACCEPT_LANGUAGE,
            'Accept-Encoding' => DiscoveryConfig::ACCEPT_ENCODING,
        ];
        $etag = trim((string) ($validators['etag'] ?? ''));
        $lastModified = trim((string) ($validators['last_modified'] ?? ''));
        if ($etag !== '' && strlen($etag) <= 200) {
            $headers['If-None-Match'] = $etag;
        }
        if ($lastModified !== '' && strlen($lastModified) <= 64) {
            $headers['If-Modified-Since'] = $lastModified;
        }

        return $request->timeout(DiscoveryConfig::TIMEOUT_SECONDS)
            ->connectTimeout(DiscoveryConfig::CONNECT_TIMEOUT_SECONDS)
            ->withOptions([
                'allow_redirects' => false,
                'http_errors' => false,
                'version' => 1.1,
                'cookies' => false,
                // Guzzle decodes the gzip body because Accept-Encoding is set.
                'decode_content' => true,
            ] + ($ipv4 ? ['force_ip_resolve' => 'v4'] : []))
            ->withHeaders($headers);
    }

    /** The host refuses this server's IPv6 address (2026-10-09, Avrupadent): its requests go over IPv4 for 30 days. */
    public static function preferIpv4(string $host): void
    {
        if ($host !== '') {
            Cache::put('public-http:ipv4:'.mb_strtolower($host), true, now()->addDays(30));
        }
    }

    public static function prefersIpv4(string $host): bool
    {
        return $host !== '' && (bool) Cache::get('public-http:ipv4:'.mb_strtolower($host), false);
    }

    /**
     * Whether the site's page cache served this response, from its headers and the cache plugins' footer comments.
     * `hit` is null when nothing says either way.
     *
     * @param  array<string, mixed>  $headers  response headers (any case; values string or list)
     * @return array{hit: ?bool, plugin: ?string}
     */
    public static function cacheSignal(array $headers, ?string $body = null): array
    {
        $h = [];
        foreach ($headers as $name => $value) {
            $h[strtolower((string) $name)] = strtolower(trim(is_array($value) ? implode(',', array_map('strval', $value)) : (string) $value));
        }
        $hit = null;
        $plugin = null;
        $verdict = static fn (string $value): ?bool => match (true) {
            str_contains($value, 'hit') => true,
            str_contains($value, 'miss') || str_contains($value, 'bypass') || str_contains($value, 'expired') || str_contains($value, 'dynamic') || str_contains($value, 'no-cache') => false,
            default => null,
        };
        if (isset($h['x-litespeed-cache'])) {
            $plugin = 'litespeed';
            $hit = $verdict($h['x-litespeed-cache']);
        }
        if (isset($h['cf-cache-status'])) {
            if (isset($h['cf-apo-via']) || isset($h['cf-edge-cache'])) {
                $plugin ??= 'cloudflare_apo';
            }
            $hit = $hit === true ? true : ($verdict($h['cf-cache-status']) ?? $hit);
        }
        foreach (['x-cache', 'x-proxy-cache', 'x-cache-status', 'x-sg-cache', 'x-nginx-cache'] as $name) {
            if (isset($h[$name]) && $hit !== true) {
                $hit = $verdict($h[$name]) ?? $hit;
            }
        }
        if (isset($h['x-wp-super-cache']) || isset($h['wp-super-cache'])) {
            $plugin ??= 'wp_super_cache';
            $hit = true;
        }
        if (isset($h['x-rocket-nginx-serving-static'])) {
            $plugin ??= 'wp_rocket';
        }
        if (str_contains($h['x-powered-by'] ?? '', 'w3 total cache')) {
            $plugin ??= 'w3_total_cache';
        }
        if ($hit !== true && isset($h['age']) && ctype_digit($h['age']) && (int) $h['age'] > 0) {
            $hit = true;
        }
        if (is_string($body) && $body !== '') {
            // The cache plugins' comments sit at the very end of the page.
            $tail = substr($body, -4096);
            foreach (self::CACHE_FOOTER_MARKERS as $marker => $name) {
                if (stripos($tail, $marker) === false) {
                    continue;
                }
                $plugin ??= $name;
                // W3 Total Cache also writes its comment on pages it did not serve from the cache.
                $refused = $name === 'w3_total_cache' && preg_match('/rejected|not cached|user is logged in/i', $tail) === 1;
                $hit = $refused ? ($hit ?? false) : true;
            }
        }

        return ['hit' => $hit, 'plugin' => $plugin];
    }

    /** A validator header of a response (ETag / Last-Modified) for the next conditional request. */
    private static function validator(Response $response, string $name): ?string
    {
        $value = $response->header($name);
        $value = is_string($value) ? trim($value) : '';

        return $value !== '' && strlen($value) <= 200 ? $value : null;
    }

    /**
     * One hop's response: the next redirect target, or the final result.
     *
     * @return array{next: string}|array{result: array{ok: bool, requested_url: string, final_url: ?string, status_code: ?int, content_type: ?string, body: ?string, bytes: int, redirect_count: int, error: ?string}}
     */
    private function evaluate(string $url, string $current, int $redirects, Response $response, int $maxResponseBytes): array
    {
        $status = $response->status();

        if ($status === 304) {
            // Conditional request: the page did not change since the stored copy.
            return ['result' => [
                'ok' => true,
                'requested_url' => $url,
                'final_url' => $current,
                'status_code' => 304,
                'content_type' => null,
                'body' => null,
                'bytes' => 0,
                'redirect_count' => $redirects,
                'error' => null,
                'not_modified' => true,
                'etag' => self::validator($response, 'ETag'),
                'last_modified' => self::validator($response, 'Last-Modified'),
                'cache' => self::cacheSignal($response->headers()),
            ]];
        }

        if (in_array($status, [301, 302, 303, 307, 308], true)) {
            $location = $response->header('Location');
            if (! is_string($location) || trim($location) === '') {
                return ['result' => $this->failure($url, 'redirect_missing_location', $current, $redirects)];
            }

            $next = $this->normalizer->resolve($current, $location);
            if ($next === null) {
                return ['result' => $this->failure($url, 'redirect_invalid_location', $current, $redirects, $status)];
            }

            if ($redirects + 1 > DiscoveryConfig::MAX_REDIRECTS) {
                return ['result' => $this->failure($url, 'redirect_limit_exceeded', $current, $redirects + 1, $status)];
            }

            return ['next' => $next];
        }

        $contentType = $response->header('Content-Type');
        $contentType = is_string($contentType) ? strtolower(trim(explode(';', $contentType)[0])) : null;

        if ($contentType !== null && ! $this->isAllowedContentType($contentType)) {
            return ['result' => $this->failure($url, 'unsupported_content_type: '.$contentType, $current, $redirects, $status, $contentType)];
        }

        $contentLength = $response->header('Content-Length');
        if (is_string($contentLength) && ctype_digit($contentLength) && (int) $contentLength > $maxResponseBytes) {
            return ['result' => $this->failure($url, 'response_too_large', $current, $redirects, $status, $contentType)];
        }

        $body = $response->body();
        $bytes = strlen($body);

        if ($bytes > $maxResponseBytes) {
            return ['result' => $this->failure($url, 'response_too_large', $current, $redirects, $status, $contentType)];
        }

        $ok = $status < 400;
        // WordPress answers "Error establishing a database connection" when the host runs out of database
        // connections; that page is never stored as the page's content and tells the crawler to slow down.
        $databaseDown = self::isDatabaseErrorPage($status, $body);
        $error = $ok ? null : 'http_'.$status;
        if ($databaseDown) {
            $ok = false;
            $error = ($error !== null ? $error.':' : '').self::DATABASE_ERROR;
        }

        return ['result' => [
            'ok' => $ok,
            'requested_url' => $url,
            'final_url' => $current,
            'status_code' => $status,
            'content_type' => $contentType,
            'body' => $ok ? $body : null,
            'bytes' => $bytes,
            'redirect_count' => $redirects,
            'error' => $error,
            'not_modified' => false,
            'etag' => $ok ? self::validator($response, 'ETag') : null,
            'last_modified' => $ok ? self::validator($response, 'Last-Modified') : null,
            'cache' => self::cacheSignal($response->headers(), $ok ? $body : null),
        ]];
    }

    /** A server error page (or a tiny 200 page) that carries WordPress's database-connection error. */
    public static function isDatabaseErrorPage(int $status, string $body): bool
    {
        if ($status < 500 && strlen($body) > 8192) {
            return false;
        }
        foreach (self::DATABASE_ERROR_MARKERS as $marker) {
            if (stripos($body, $marker) !== false) {
                return true;
            }
        }

        return false;
    }

    private function isAllowedContentType(string $contentType): bool
    {
        return str_contains($contentType, 'text/html')
            || str_contains($contentType, 'application/xhtml')
            || str_contains($contentType, 'application/xml')
            || str_contains($contentType, 'text/xml')
            || str_contains($contentType, '+xml')
            || str_contains($contentType, 'application/json')
            || str_contains($contentType, '+json')
            || str_contains($contentType, 'text/plain');
    }

    /**
     * @return array{
     *     ok: bool,
     *     requested_url: string,
     *     final_url: ?string,
     *     status_code: ?int,
     *     content_type: ?string,
     *     body: ?string,
     *     bytes: int,
     *     redirect_count: int,
     *     error: ?string
     * }
     */
    private function failure(
        string $requested,
        string $error,
        ?string $final = null,
        int $redirects = 0,
        ?int $status = null,
        ?string $contentType = null,
    ): array {
        return [
            'ok' => false,
            'requested_url' => $requested,
            'final_url' => $final,
            'status_code' => $status,
            'content_type' => $contentType,
            'body' => null,
            'bytes' => 0,
            'redirect_count' => $redirects,
            'error' => $error,
        ];
    }
}
